spring:
  application:
    name: keycloak-auth
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: 'http://localhost:8080/realms/SpringBootDemoKeyCloak'
          jwk-set-uri: >-
            ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
jwt:
  auth:
    converter:
      resource-id: springboot-keycloak-demo-client
      priciple-attribute: preferred_username
server: 'port:8081'

logging:
  level:
    org.springframework.security: DEBUG